version: "3.9"
services:
  api:
    container_name: 'api-slt'
    build: './Funeral-Home-Management/'
    ports:
      - "8090:8090"
    depends_on:
      - database
    restart: always
    expose:
      - 8090
  database:
    container_name: 'mysql-FuneralHomeMnt'
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: FuneralHomeMnt
    expose:
      - 3306